<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="4076" started-at="2018-04-08T16:50:40Z" finished-at="2018-04-08T16:50:44Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="4076" started-at="2018-04-08T16:50:40Z" finished-at="2018-04-08T16:50:44Z">
      <class name="test_cases.PingdomTest">
        <test-method status="PASS" signature="loadConfig()[pri:0, instance:test_cases.PingdomTest@396e2f39]" name="loadConfig" is-config="true" duration-ms="7" started-at="2018-04-08T16:50:40Z" finished-at="2018-04-08T16:50:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method status="PASS" signature="init_driver()[pri:0, instance:test_cases.PingdomTest@396e2f39]" name="init_driver" is-config="true" duration-ms="3214" started-at="2018-04-08T16:50:40Z" finished-at="2018-04-08T16:50:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init_driver -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:test_cases.PingdomTest@396e2f39]" name="test1" duration-ms="8" started-at="2018-04-08T16:50:43Z" finished-at="2018-04-08T16:50:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at test_cases.PingdomTest.test1(PingdomTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test_cases.PingdomTest@396e2f39]" name="teardown" is-config="true" duration-ms="840" started-at="2018-04-08T16:50:43Z" finished-at="2018-04-08T16:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- test_cases.PingdomTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
